### ISSUE TITLE
Support ~

### ISSUE THREAD

**Issue by paulomcnally** [styled-components/styled-components#1190]
https://www.styled-components.com/docs/api#supported-css don't have **~** information.

I need:
```css
.input:focus ~ .highlight {
  -webkit-animation: inputHighlighter 0.3s ease;
  -moz-animation: inputHighlighter 0.3s ease;
  animation: inputHighlighter 0.3s ease;
}
```

I have input and highlight.
