### ISSUE TITLE
Minify the getStyleElement() output

### ISSUE THREAD

**Issue by kachkaev** [styled-components/styled-components#1217]
Hi guys,

I'm using [Next.js with styled-components](https://github.com/zeit/next.js/tree/master/examples/with-styled-components) and it’s great that I can get a fully-rendered HTML with all the required CSS from the server!

After looking at the source code of the pages that arrive to the client, I noticed that there is probably some scope for improvement. Check out the output of `styled-components`’ `sheet.getStyleElement()` compared to the rest of the server-rendered content:

![styled-components getStyleElement()](https://user-images.githubusercontent.com/608862/31316258-ee6cbe48-ac21-11e7-947e-4e4d50e3f031.png)

A closer look reveals something like:

```css
/* sc-component-id: Locale__LinkToLocale-zq7758-1 */

.bepDJp{margin-left:8px;}
/* sc-component-id: LocaleToggler__Wrapper-s164faf9-0 */

.eyEkZV{position:absolute;top:12px;right:25px;}
/* sc-component-id: LinkToSource__Wrapper-s1y1z1az-0 */

.dqQlOP{position:absolute;bottom:12px;right:25px;}
/* sc-component-id: withLayout__Wrapper-s1mfcftp-0 */
```

As you can see, about a half of the content consists of comments, which are not very useful in production environemnt. Depending on the page structure, this may lead to several extra kilobytes transferred to each client with no purpose.

To make things a bit more efficient, I added a pretty dirty hack that removes comments and newlines from the output like this: 

```js
const styleTags = sheet.getStyleElement();
styleTags[0].props.dangerouslySetInnerHTML.__html =
    styleTags[0].props.dangerouslySetInnerHTML.__html
        .replace(/\/\*.*\*\//g, ' ')
        .replace(/\s+/g, ' ');
```
↓
```css
.bepDJp{margin-left:8px;} .eyEkZV{position:absolute;top:12px;right:25px;} .dqQlOP{position:absolute;bottom:12px;right:25px;}
```

However, I’m wondering if the size of the output could be reduced in a less barbarous way, say, by configuring `getStyleElement`:

```js
const styleTags = sheet.getStyleElement({
    compact: process.NODE_ENV === 'production',
});
```

WDYT?
