### ISSUE TITLE
@supports (position: sticky) doesn't work

### ISSUE THREAD

**Issue by denkristoffer** [styled-components/styled-components#1230]
## Version
2.2.1
Stylis version 3.3.0 according to Yarn.lock

## Reproduction

https://www.webpackbin.com/bins/-Kw94RvoR349Ae5c3rRt

## Steps to reproduce
Create a component like
```css
const Title = styled.h1`
  background: blue;

  @supports (position: sticky) {
    background: red;
  }
`;
```

## Expected Behavior
https://stylis.js.org/ generates the following output:
```css
.title {
	background: blue;
}

@supports (position:-webkit-sticky)or(position:sticky) {
	.title {
		background: red;
	}
}

```

SC would be expected to generate something similar and inject it into `<head>`.

## Actual Behavior
The following style tag gets injected into `<head>` in the WebpackBin example:

```css
.sc-bdVaJa {}.jXrxxY {background: blue;}@supports (position: sticky) {background: red;}
```

As you can see the scope seems to get messed up. The prefixed option that stylis generates is also missing.

**Comment by thysultan** [comment]
Is it also 3.3.0 in node_modules, since vendor prefixing properties in `@supports (position: sticky)` was introduced in a recent 3.X.X patch it might be a version issue.

Can't say i know why the scope is omitted for the `@support` block. @mxstbr is s-c using the `insertRule` API in this version?

**Comment by mxstbr** [comment]
No, we haven't merged that yet.

**Comment by denkristoffer** [comment]
> Is it also 3.3.0 in node_modules

It is, just checked 🙂

**Comment by thysultan** [comment]
@mxstbr Do you what s-c would pass to stylis in this case?

**Comment by mxstbr** [comment]
Something like this:

```CSS
.Test-asdf123 {
 background: blue;

  @supports (position: sticky) {
    background: red;
  }
}
```
