### ISSUE TITLE
"& + &" selector, like in sass

### ISSUE THREAD

**Issue by quolpr** [styled-components/styled-components#1264]
Sass have such syntax:

```sass
.selector {
  & + & {
    color: #000;
  }
}
```

Which will be converted to:

```css
.selector + .selector {
  color: #000;
}
```

But as I understand styled-components don't support this feature. Is there any chance that it will be implemented, so this code

```
styled.div`
  & + & {
    color: #000;
  }
`;
```

 will be working right?
