### ISSUE TITLE
Styling placeholders (potentially others)

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#13]
This currently does not work at all, because our "parser" doesn't support it:

```CSS
::-webkit-input-placeholder {
  some: styles;
}
```

Possibly related to #6 if we end up implementing the PostCSS parser
