### ISSUE TITLE
Duplicate CSS rules are generated for read-only modifier due to -moz- vendor prefix

### ISSUE THREAD

**Issue by doque** [styled-components/styled-components#1338]
## Version
2.2.4

Adding styles for the read-only modifier results in a duplicate CSS rule:

```js
const InputField = styled.input`
  &:read-only,
  &:disabled {
    background: lightgray;
  }
  &::after {
    content: "no"
  }
}
`;
```
results in

```css
.c0:-moz-read-only,
.c0:disabled {
  background: lightgray;
}

.c0:read-only,
.c0:disabled {
  background: lightgray;
}

.c0::after {
  content: "no";
}
```

It seems that this is caused by the `-moz-` prefix.

## Reproduction

I've set up a sample repository [here](https://github.com/doque/styled-components-duplicate-rules).

## Steps to reproduce
Run `npm test` and inspect `src/App/__snapshot__/App.test.js.snap`

## Expected Behavior
Only one CSS rule should be generated:
```css
.c0:-moz-read-only,
.c0:read-only,
.c0:disabled {
  background: lightgray;
}
```

## Actual Behavior
Multiple rules are generated:
```css
.c0:-moz-read-only,
.c0:disabled {
  background: lightgray;
}

.c0:read-only,
.c0:disabled {
  background: lightgray;
}
```

**Comment by philpl** [comment]
This seems to be an issue in stylis.

@doque Does this lead to any adverse effects? It looks to me like it would still behave fine.

cc @thysultan: It seems that there's a small quirk here that duplicates rules to prefix selectors instead of adding them. Is this intended behaviour actually?

**Comment by doque** [comment]
@philpl You're right, it still works fine. But I'd still like to avoid the code duplication, if possible. Should I move this issue to the stylis repo?

**Comment by thysultan** [comment]
>Is this intended behaviour actually?
 
@philpl Not sure, but i'll look into it.

>Should I move this issue to the stylis repo?

@doque Yes, i think this only affects `:read-only` and `:placeholder`.

**Comment by thysultan** [comment]
Yes this is actually intended behavior, it wouldn't work otherwise.

```css
input:-moz-placeholder,
input::placeholder{color:red;background:green;}
```
does not work, whereas the following css does...

```css
input:-moz-placeholder{color:red;background:green;}
input::placeholder{color:red;background:green;}
```
```
[autoprefixer](http://autoprefixer.github.io/) does the same thing.
