### ISSUE TITLE
Managing highly dynamic styles

### ISSUE THREAD

**Issue by JamieDixon** [styled-components/styled-components#134]
Example component:

```
const Comp = styled.div`
     /*lots of styles here*/
     animation-delay: ${ props => props.index * 0.1 };
`;
```

With this component rendered over a collection of items, we'll generate a new style tag with an associated class for each one.

Is there a recommended way of working with these kinds of styles so as not to thrash the head with  a new `style` tag everytime `render` is called on `Comp`?
- One solution could be to move the `/* lots of styles here */` into another component that doesn't include the dynamic properties that cause huge amounts of CSS to be rendered into the `head`. This way the generated `style` tag only contains the `animation-delay` property. Still a lot of `style` tags being injected into the head though and since the injection only happens at render time, this could cause some trashing.
- Another option is to put the `animationDelay` into the `style` prop of the component as we compose the components and not let styled-components handle this.

How would you do this? Is there a recommended approach?

I saw there might be some plans to extract static styles which, as a solution, is similar to our first option above.

**Comment by JamieDixon** [comment]
On the other hand, it could be that we're trying to do things with `styled-components` that it's just not designed for.

Another option would be to use something like `Velocity` to handle our animations and `styled-components` for the rest.

**Comment by mxstbr** [comment]
Have you noticed any visible performance impact on the animation with the current way? If so, could you provide a reproduction in a webpack bin?

**Comment by mikepombal** [comment]
Hi @mxstbr,

No performance impact but duplication of the same style again and again which increases the bundle size. Following @JamieDixon example if we have a list of `Comp` components the style created will be the following:
```css
.[generated class name for 1st instance of comp] {
    /*lots of styles here*/
    animation-delay: 0s;
}
.[generated class name for 2nd instance of comp] {
    /*lots of styles here*/
    animation-delay: 0.1s;
}
.[generated class name for 3rd instance of comp] {
    /*lots of styles here*/
    animation-delay: 0.2s;
}
/* and so on */
```
As you see the `/*lots of style here*/`, although it is the same style, appears n times the number of items in the list.

I'm wondering if #59 could actually fix this issue.
