### ISSUE TITLE
Rule flattening edge case

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1517]
```css
const Foo = styled.input`
    &::placeholder {
        color: blue;

        &:focus {
            color: red;
        }
    }
`;
```

Flattens to `.{hash}::placeholder:focus { }` instead of `.{hash}:focus::placeholder { }`

This isn't valid CSS, BUT it's something I could see people accidentally doing often.

Is this something we can handle ourselves? If not, should it be a linting rule?
