### ISSUE TITLE
Module to write styled and output html and css without using react

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#1689]
We have some case where we do not have react and only HTML and CSS, sometimes just a div and a class.

It would be convenient to maintain and test our components using styled. 

How can I produce when I write this in `src/MyDiv.js`

```js
const MyDiv = styled.div`
  border: 1px solid red;
  width: 50px;
  height: 50px;
  &:hover { 
    border: 1px solid yellow;
  }
`
myDiv.id = 'foobar';
```

and generate two files `build/MyDiv.css`

```css
.Feq456 {
    border: 1px solid red;
    width: 50px;
    height: 50px;
}
.Feq456:hover {
    border: 1px solid red;
}
```

and generate two files `build/MyDiv.html`

```html
<div id="foobar" class="Feq456"></div>
```

I would like to do that with an entire rollup project, is there any tool or any recommendation to get from here ?
