### ISSUE TITLE
Inner style overwrites outer style

### ISSUE THREAD

**Issue by philholden** [styled-components/styled-components#170]
## Version
1.0.10

## Reproduction
http://www.webpackbin.com/VyC-jOtxM

## Steps to reproduce
Go to link above

## Expected Behavior
Background color should be green. Outer styles should override inner styles.

## Actual Behavior
Background is red. Inner styles have precedence over outer styles.

```html
<a href="#" class="fioMWT byDUWI" data-reactid=".0.2">Click</a>
```

```css
.fioMWT {
  background: green;
}

.byDUWI {
  background: red;
  display: inline-block;
  border: none;
  font: 16px cursive;
  padding: 5px;
  border-radius: 5px;
  text-decoration: none;
  color: black;
}
```

Is there a better way to pass a element type in as a prop and return a styled component of that type?
