### ISSUE TITLE
[V3-V4] migrating our keyframes, inline styles are now broken.

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#2276]
We are updating an old library that use a lot of keyframes from styled-components v3 to styled-components v4.

1. We use a `makeKeyframe` function that give back the keyframe classame.
2. We use that classname to create an inline style.

It use to look like this:

```js
const keyframeName = makeKeyframe(this.makeAnimation, { distance, rotation, perspective, amplification }, props.keyframes);
styles.animation = ` ${keyframeName} ${duration} ${timingFunction} ${delay} ${iterations} ${direction} ${fillMode} ${playState}`;
if (TYPE_ROTATE === this.makeAnimation.type) {
    styles.backfaceVisibility = backfaceVisibility;
}

// later
this.setState({
   styles,
});

// on render
return (
  <span
    className={mapToCssModules(cn({ 'd-inline-block': inline }, className), cssModule)}
    styles={this.state.styles}
  >
    {children}
  </span>
);
```

After upgrading to v4, we had the following error:

      Uncaught Error: It seems you are interpolating a keyframe declaration (bGJZDZ) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\`\` helper (see https://www.styled-components.com/docs/api#css), which ensures the styles are injected correctly.

We switched in in v4 to : 

```
let styles = css`
    animation: ${keyframeName} ${duration} ${timingFunction} ${delay} ${iterations} ${direction} ${fillMode} ${playState};
  `;

  if (TYPE_ROTATE === this.makeAnimation.type) {
    styles = css`
      ${styles}
      backface-visibility: ${backfaceVisibility};
    `;
  }
// later
this.setState({
   styles,
});

// on render
return (
  <span
    className={mapToCssModules(cn({ 'd-inline-block': inline }, className), cssModule)}
    css={this.state.styles}
  >
    {children}
  </span>
);
```

This also doesn't work.

```css
.hDnAJR {
    -webkit-undefinedanimation: bGJZDZ 500ms ease 0ms 1 normal none running;
    -ms-flex-undefinedanimation: bGJZDZ 500ms ease 0ms 1 normal none running;
    undefinedanimation: bGJZDZ 500ms ease 0ms 1 normal none running;
    -webkit-undefined: ;
    -ms-flex-undefined: ;
    undefined: ;
}
```

We did use the `css` helper, but now the injected keyframes in the pages cannot be used without react is that correct ?

Or is there a way to fix this?
