### ISSUE TITLE
webkitBoxOrient property is rendered 'webkit-box-orient' instead of '-webkit-box-orient'.

### ISSUE THREAD

**Issue by altenull** [styled-components/styled-components#2335]
## Environment

* OS: macOS Mojave 10.14.2
* CPU: 2.2 GHz Intel Core i7
* Total Memory: 16.00 GB
* Chrome 71

## Binaries

* Node: 8.13.0
* npm: 6.4.1
* react: 16.7.0

### styled-components:

wanted: ^4.1.3
installed: 4.1.3

## Reproduction

When i use styled-components as **Style Objects**, `webkitBoxOrient` css property is rendered to `webkit-box-orient` instead of `-webkit-box-orient` in browser.

* https://www.styled-components.com/docs/advanced#style-objects **(Style Objects)**

```javascript
import styled from 'styled-components';

const SampleText = styled.p({
  width: '56px',
  wordBreak: 'break-word',
  webkitBoxOrient: 'vertical', // This
});
```

```css
.isjcewa {
  width: 56px;
  word-break: break-word;
  webkit-box-orient: vertical; // Should be -webkit-box-orient ....
}
```
