### ISSUE TITLE
CSS breaks on CSS selectors with line breaks and pseudo-classes

### ISSUE THREAD

**Issue by azami** [styled-components/styled-components#2504]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

> ## System:
>  - OS: macOS High Sierra 10.13.6
>  - CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
>  - Memory: 11.10 GB / 32.00 GB
>  - Shell: 3.2.57 - /bin/bash
> ## Binaries:
>  - Node: 10.3.0 - /usr/local/bin/node
>  - Yarn: 1.7.0 - /usr/local/bin/yarn
> - npm: 6.9.0 - /usr/local/bin/npm
> ## npmPackages:
> - styled-components: 4.2.0 => 4.2.0

## Reproduction

see: https://codesandbox.io/s/kwq2pkrv67

## Steps to reproduce

Occurs under the following conditions.

- selectors have a line break
- nested selectors use pseudo-class

I do not know there may be other conditions

```css
  .foo
    .bar
    > div:not(:last-child) {
    background: pink;
  }
```

## Expected Behavior

not include line break is ok

```css
  .foo:first-child .bar > div:not(:last-child) {
    background: pink;
  }
```
output:

```css
<style data-styled="" data-styled-version="4.2.0">
/* sc-component-id: sc-bdVaJa */
.eUtAON .foo:first-child .bar > div:not(:last-child){background:pink;}</style>
```

## Actual Behavior

```css
<style data-styled="" data-styled-version="4.2.0">
/* sc-component-id: sc-bdVaJa */
.kcBvdm{.foo:first-child .bar;} .kcBvdm > div:not(:last-child){background:pink;}</style>
```
