### ISSUE TITLE
IE11 not picking up class when using SSR

### ISSUE THREAD

**Issue by topaxi** [styled-components/styled-components#2770]
### System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 9.84 GB / 32.00 GB
 - Shell: 5.7.1 - /usr/local/bin/zsh
### Binaries:
 - Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - styled-components: ^5.0.0-beta.8 => 5.0.0-beta.8-groupsizefix

## Steps to reproduce
Sadly I'm not able to properly reproduce this issue outside of our application.

## Expected Behavior
Rendered styles should be rendered by IE11.

## Actual Behavior
Using SSR, the class/rule definition is correctly rendered to the client and appended into the DOM. But IE11 doesn't seem to be able to pick up the styles in certain cases, I got an element with `class="r5r22j-0 lkVjVW"` but the style panel shows no styles being applied to the element.

The corresponding generated style rules are: 
```css
.lkVjVW{-webkit-flex-shrink:0;-ms-flex-negative:0;flex-shrink:0;height:100%;position:relative;text-align:center;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;cursor:pointer;-webkit-transition-property:-webkit-transform;-webkit-transition-property:transform;transition-property:transform;width:562.7484662576687px;}
```

I don't see anything going wrong but the result is nonetheless an element without styles 🤔. It works perfectly fine in other browsers and once I force a rerender by toggling the element it seems to be working (I assume styled-components generate a new style rule and injects new styles into the DOM).
