### ISSUE TITLE
Css classes are not splitted to treat output CSS effectively

### ISSUE THREAD

**Issue by adambisek** [styled-components/styled-components#2985]
After reading documentation and googling I nowhere found, how to make SC effective and split produced css code.

**Version of SC:**
I have this issue on SC version: 4.4.1 and also latest 5.0.0.

**Repro steps:**
I have component like this:

```javascript
const StyledInput = styled.input`
  box-sizing: border-box;
  border: slim;
  border-color: red;
  color: ${(props: any) => myfunction(props.color || 'black')};
  width: 100%;
`
```

And I use it two times like this:

```javascript
<StyledInput color="red" />
<StyledInput color="green" />
```

**Current CSS output:**
```css
.class1 {
  box-sizing: border-box;
  border: slim;
  border-color: red;
  color: red;
  width: 100%;
}
.class2 {
  box-sizing: border-box;
  border: slim;
  border-color: green;
  color: red;
  width: 100%;
}
```

**Expected CSS output:**
```css
.commonClass {
  box-sizing: border-box;
  border: slim;
  border-color: red;
  width: 100%;
}
.class1 {
  color: red;
}
.class2 {
  color: red;
}
```
