### ISSUE TITLE
styled component with stylis-atomic generates invalid css 

### ISSUE THREAD

**Issue by hrasoa** [styled-components/styled-components#3069]
## Reproduction
I was trying to use ``` stylis-atomic```, but it generates invalid css. I don't know if it comes from styled component or stylis.
* https://codesandbox.io/s/gifted-haslett-9p7li
* preview: https://9p7li.csb.app/

## Steps to reproduce
Just launch the app and inspect the generated stylesheet.

## Expected Behavior
```css
.bWlJJP{display:'block';}
.iSeJOe{display:'block';}
.iSeJOe{background-color:red;}
```

## Actual Behavior
```css
.bWlJJP{display:'block';}} /* <-- double bracket */
.iSeJOe{display:'block';}
.iSeJOe{background-color:red;}} /* <-- double bracket */
```
