### ISSUE TITLE
How to style child element that depends on parent ?

### ISSUE THREAD

**Issue by SanskarSans** [styled-components/styled-components#330]
I have my component of table like this 

```javascript
<Table className="table">
  <Thead>
    <Tr>
      <Th>ID</Th>
      <Th>Name</Th>
    </Tr>
  </Thead>
  <Tbody>
    <Tr>
      <Td>1</Td>
      <Td>Material Design</Td>
    </Tr>
  </Tbody>
</Table>
```

How can i apply such css?

```css
.table > thead > tr > th,
.table > tbody > tr > td,
{
  text-align: left;
  padding: 20px;
  vertical-align: top;
  border-top: 0;
}
```
