### ISSUE TITLE
Regression: generated class names relating to props are not surviving nesting

### ISSUE THREAD

**Issue by tremby** [styled-components/styled-components#3330]
## Description

Since version 5.0.1, generated class names describing a matched set of props don't survive selector nesting.

Example:

```js
const Box = styled.div`
  ${({ variant }) => variant === "colourful" && css`
    border: 1px solid black;
    margin: 1rem;
    padding: 1rem;

    color: red;
    .make-red-green & {
      color: green;
    }
  `}
`;

const App = () => (
  <div className="make-red-green">
    <Box variant="colourful">Should be green</Box>
    <Box>Should have default colour (black)</Box>
  </div>
);
```

This is outputting

```html
<div class="make-red-green">
  <div class="sc-gsTCUz ldlxmw">Should be green</div>
  <div class="sc-gsTCUz iuQOzC">Should have default colour (black)</div>
</div>
```

with

```css
.ldlxmw {
 border:1px solid black;
 margin:1rem;
 padding:1rem;
 color:red;
}
.make-red-green .sc-gsTCUz {
 color:green;
}
.iuQOzC {
 border:1px solid black;
 margin:1rem;
 padding:1rem;
}
```

But that output CSS for the rule which makes the text green does not take into account the `variant === "colourful"` constraint. The CSS output should be

```css
.ldlxmw {
 border:1px solid black;
 margin:1rem;
 padding:1rem;
 color:red;
}
.make-red-green .ldlxmw {
 color:green;
}
.iuQOzC {
 border:1px solid black;
 margin:1rem;
 padding:1rem;
}
```

Both versions of CSS above duplicate more than they should, which seems wasteful, but that's not the issue at hand.

## Reproduction

The above code is used here:

https://codesandbox.io/s/styled-components-bug-reproduction-85wlm?file=/index.js

## Steps to reproduce

Consider reproduction.

## Expected behaviour

First box's text should be green.
Second box's text should have default text colour (black).

## Actual behaviour

First box's text is green (correct).
Second box's text is green (bug).

## Version scope

5.0.0 did not have the bug.
5.0.1 has the bug.
Bug remains in current version (5.2.1)
