### ISSUE TITLE
Feature request: Support extending styles by classNames.

### ISSUE THREAD

**Issue by lext-7** [styled-components/styled-components#3339]
**Case:**
I want to extract some common style as utils, such as follow:
```tsx
import styled, { css } from "styled-components";

import "./styles.css";

const flexCenter = css`
  display: flex;
  align-items: center;
  jusitfy-content: center;
`;

const Button1 = styled.button`
  ${flexCenter}
  background: #eee;
`;
```

The styles of `Button1` will be：
```css
.button {
  display: flex;
  align-items: center;
  jusitfy-content: center;
  background: #eee;
}
```

**Problem:**
Rules in `flexCenter` will be copied into Button1, which will cause a lots of duplicated styles. And The more `flexCenter` is used, the larger file size.

**Solution(maybe):**

Can we extract those common styles into css classes, then reuse them by referring class name. Such as follow
```css
.flexCenter {
  display: flex;
  align-items: center;
  jusitfy-content: center;
}

.button {
  background: #eee;
}
```

```html
<button1 class="flexCenter button1" />
```
