### ISSUE TITLE
Escape colon on class names

### ISSUE THREAD

**Issue by hugo-licon** [styled-components/styled-components#3613]
I'm trying to replicate the [Tailwind syntax for responsive spacing](https://tailwindcss.com/docs/margin#responsive)
The syntax is this: `m-{size}` and for the responsive is this: `{screen}:m-{size}`

So I created these classes using styled-components
```CSS
.m-1 {
  margin: 4px;
}
.m-4 {
  margin: 16px;
}
@media (min-width: 768px) {
  .md\:m-1 {
    margin: 4px;
  }
  .md\:m-4 {
    margin: 16px;
  }
}
`;
```
And used them like so:
```javascript
<Container className="App">
  <BlueBox className="m-1 md:m-4" />
  <RedBox />
</Container>
```
but the `md:m-4` class doesn't seem to work, but, if I defined the same classes on a CSS file it does work.

## Reproduction
You can find the complete code on this code sanbox:
https://codesandbox.io/s/styled-components-issue-tbhbt?file=/src/App.jsx

I don't know if I'm not escaping the class names correctly or if it is something that styled-component doesn't support yet.
