### ISSUE TITLE
attributes selector in styled-components

### ISSUE THREAD

**Issue by KnowsCount** [styled-components/styled-components#3703]
after doing a bit of research, I could not find information regarding the usage of attribute selectors (that is, `[attr=value]`) in styled-components. however, I still imagine it is highly possible for styled-components to support attribute selectors... but should it not, what are some equivalents of it?

for instance, if I have the code below

```css
.squares li[data-level='1'] {
	background-color: var(--light);
}

.squares li[data-level='2'] {
	background-color: var(--medium);
}

.squares li[data-level='3'] {
	background-color: var(--dark);
}

.squares li[data-level='4'] {
	background-color: var(--darkest);
}
```

how do I achieve it via `styled-components`?

### System:
 - OS: macOS 12.0.1
 - CPU: (8) arm64 Apple M1
 - Memory: 126.97 MB / 8.00 GB
 - Shell: 5.8 - /bin/zsh
### Binaries:
 - Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
 - Yarn: 1.22.17 - ~/.yvm/shim/yarn
 - npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
### npmPackages:
 - styled-components: ^5.3.3 => 5.3.3
