### ISSUE TITLE
`&` is implicitly applied in front of `:where()` even if `:where()` contains `&`

### ISSUE THREAD

**Issue by matthew-dean** [styled-components/styled-components#3723]
Codesandbox example: https://codesandbox.io/s/styled-components-forked-pjlt3o?file=/Title.js

## Steps to reproduce

With this markup:
```jsx
    <Title>
      <span>Hello World, this is my first styled component!</span>
    </Title>
```
...style Title like:
```jsx
export default styled.h1`
  :where(& span) {
    font-size: 1.5em;
    text-align: center;
    color: palevioletred;
  }
`;
```
## Expected Behavior
The docs show this as an example:
```scss
  .something-else & {
    border: 1px solid; // <Thing> inside another element labeled ".something-else"
  }
```
This implies that the existence of `&` will not apply it before `.something-else`

## Actual Behavior
`:where(& span)` is interpreted like `&:where(& span)`, meaning the `span` cannot be matched, because it can't be both the root element and the child of the root element.
