### ISSUE TITLE
Using rgba in box-shadow generates strange values

### ISSUE THREAD

**Issue by alexojegu** [styled-components/styled-components#3735]
## Environment
```
## System:
 - OS: Linux 5.15 Arch Linux
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
 - Memory: 9.67 GB / 15.53 GB
 - Container: Yes
 - Shell: 5.1.16 - /bin/bash
## Binaries:
 - Node: 16.14.2 - /usr/bin/node
 - npm: 8.5.5 - /usr/bin/npm
```

## Reproduction

I have this code:

```jsx
export default styled.section`
  padding: 4em;
  background: rgba(255, 239, 213, 0.9);
  box-shadow: 2px 2px 2px 2px rgba(255, 0, 0, 0.5);
`;
```

When I inspect my code on Chromium (100.0.4896.127) I see `box-shadow: 2px 2px 2px 2px rgb(255 0 0 / 50%);` this not seems a RGBA color or a RGB valid color. The background color works as expected.

## Steps to reproduce

See `Wrapper.js`: https://codesandbox.io/s/styled-components-base-forked-d95be2

## Expected Behavior

```css
.cBAopR {
    padding: 4em;
    background: rgba(255,239,213,0.9);
    box-shadow: 2px 2px 2px 2px rgba(255,0,0,0.5);
}
```

## Actual Behavior

```css
.cBAopR {
    padding: 4em;
    background: rgba(255,239,213,0.9);
    box-shadow: 2px 2px 2px 2px rgb(255 0 0 / 50%);
}
```
