### ISSUE TITLE
@container is messed up

### ISSUE THREAD

**Issue by thany** [styled-components/styled-components#3911]
## Environment

```
## System:
 - OS: Windows 10 10.0.19045
 - CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
 - Memory: 13.41 GB / 31.68 GB
## Binaries:
 - Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
 - npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^5.3.6 => 5.3.6
```

## Reproduction

Let's try a few syntaxes:
```javascript
const Div = styled.div`
  container-type: inline-size;
  container-name: div-container;

  @container waste-stream-chooser (max-width: 1000px) {
    background: hotpink;
  }
`;
```
Or:
```javascript
const Div = styled.div`
  container-type: inline-size;
  container-name: div-container;

  @container waste-stream-chooser (max-width: 1000px) {
    & {
      background: hotpink;
    }
  }
`;
```
Or:
```javascript
const Div = styled.div`
  container-type: inline-size;
  container-name: div-container;

  @container waste-stream-chooser (max-width: 1000px) {
    .another {
      background: hotpink;
    }
  }
`;
```

## Steps to reproduce

Use the above component in an application. Doesn't matter what or where.

## Expected Behavior

It generates correct CSS and doesn't mess up the `@container` block.

## Actual Behavior

It generates incorrect CSS, which causes the container query to completely break.

In order of the above examples, it generated the following incorrect output:

```css
.kNXntJ {
 container-type:inline-size;
 container-name:div-container;
}
@container div-container (max-width:1000px) {
 background:hotpink;
}
/*|*/
}
```
First example. The last two lines, that weird comment and an additional `}`, are generated only when `@container` is used. Also the contents of the container query fail to be wrapped by a `.kNXntJ { ... }` block, as it would in a `@media` query which works fine.

```css
.kNXntJ {
 container-type:inline-size;
 container-name:div-container;
}
@container div-container (max-width:1000px) {
 background:hotpink;
}
/*|*/
}
```
For the second example, identical output. The fact that I put a `& { ... }` in an attempt to wrap the contents of the contianer query with the correct classname, is totally ignored and omitted for some reason.

```css
.kNXntJ {
 container-type:inline-size;
 container-name:div-container;
}
@container div-container (max-width:1000px) .another {
 background:hotpink;
}
/*|*/
}
```
For the third example, the opening `{` is lost, breaking its syntax yet again.

I would propose to make container queries just do *exactly* what media queries do currently. Just make it absolutely 100% identical to how `@media` functions in terms of SC, at least for now, so that at least it doesn't break syntax. Not breaking syntax seems like the first priority. Fancy magic can wait, if needed.

Please note, I have noticed this is being worked on in the next version, or in some kind of prerelease version. That's fine. This is simply about the bug that breaks syntax. Like I said, fancy magic to support container queries in a really nice and convenient fancy styled-components kind of way, is fine to wait for the next version. Right now what's important is to not break syntax.
