### ISSUE TITLE
Support for cascade layers 

### ISSUE THREAD

**Issue by lanwin** [styled-components/styled-components#3950]
I tried to play around with cascade layers https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers and noticed that styled-components did not seems to have support for it.

## Reproduction

Styled-components: 5.3.6

```javascript
const MyButton = styled.button`
  @layer test {
    color: red;
  }
`;
```

This leads to the following style gets added

```css
@layer test{color:red;}
```

instead of

```css
@layer test{  
  .generatedbuttonclass { color:red; }
}
```

I am wondering that I did not found anything about that in issue tracker and discussions.
