### ISSUE TITLE
@container queries not working in v6.0.0-rc.2

### ISSUE THREAD

**Issue by MikelMNJ** [styled-components/styled-components#4024]
Hello,

It's very possible I'm missing something, if so please let me know the proper flow for implementing `@container` queries with v6 and close.

**Version**: 6.0.0-rc.2

**Expected behaviour**: flex direction should change when the `StyledDiv` `.someChildren` container size is <= 10rem.
```css
const StyledDiv = styled('div')`
  .someChildren {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
  };

  @container (max-width: 10rem) {
    .someChildren {
      flex-direction: column;
    }
  }
`;
```

**Result**: My VSCode shows the lint error `Unknown at rule @container ts-styled-plugin(9999)` and the result never occurs in the browser.

Are `@container` queries working in v6?
