### ISSUE TITLE
Lockfile diff is huge for v6

### ISSUE THREAD

**Issue by kachkaev** [styled-components/styled-components#4064]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown`

```yaml
## System:
 - OS: macOS 13.4.1
 - CPU: (10) arm64 Apple M1 Max
 - Memory: 315.94 MB / 32.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
 - Yarn: 4.0.0-rc.46 - ~/.nvm/versions/node/v18.16.0/bin/yarn
 - npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
 - Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman 
```

## Reproduction

https://github.com/kachkaev/njt/pull/374
Next.js + TypeScript + Styled Components

## Steps to reproduce

1. Upgrade `styled-components` from `5.3.11` to `6.0.1`
2. See the [diff](https://github.com/kachkaev/njt/commit/0f2820ab887b943884443b5a1e716715f596751d) in `yarn.lock` (`pnpm-lock.yaml` etc.?)

## Expected Behavior

I have expected the lockfile to change insignificantly

## Actual Behavior

[![](https://github.com/styled-components/styled-components/assets/608862/2a8beaab-e600-47f5-a8bd-526ed8f9d023)](https://github.com/kachkaev/njt/commit/0f2820ab887b943884443b5a1e716715f596751d)

The number of app dependencies has increased from 502 to 705 (+40%). This can noticeably slow down local dev and CI in a project.

Can it be that some `devDependencies` have been accidentally added to `dependencies`? It’d be nice to see a smaller diff, it is otherwise a bit scary to upgrade because the diff feels off.
