### ISSUE TITLE
Using the webpack raw-loader to bundle third-party Bootstrap CSS into 'createGlobalStyle', some styles are lost

### ISSUE THREAD

**Issue by Orcus2021** [styled-components/styled-components#4134]
### System:
- OS: macOS Ventura 13.1
- CPU: M1 Pro
- Memory: 32GB
### Binaries:
- Node: v16.19.0
- Yarn: v1.22.15
- npm: v8.19.3
### npmPackages:
- styled-components: ^5.3.0 → 5.3.1
- babel-plugin-styled-components: ^1.12.0 → 1.13.2
- webpack: ^5.76.0 → 5.76.0
- bootstrap: 4.0.0
## Reproduction
When I use the webpack raw-loader to bundle third-party Bootstrap CSS (Cascading Style Sheet) and place it into createGlobalStyle, some styles are lost. This is because some CSS selectors' styles are removed, combining selectors together.
```javascript
// places where createGlobalStyle and bootstrap are used
import { createGlobalStyle } from 'styled-components';
import bootstrapStyle from '!!bootstrap/dist/css/bootstrap.css?raw';

const GlobalStyle = createGlobalStyle`
  ${bootstrapStyle}
`;

const BootstrapLayout = ({ children }) => (
  <>
    <GlobalStyle />
    {children}
  </>
);

//FooComponent
import React from 'react'

export default function FooComponent() {
  return (
    <div className="alert alert-primary" role="alert">
      This is a primary alert—check it out!
    </div>
  )
}
```
- webpack config
```javascript
module.exports = {
  module: {
    rules: [
      {
        resourceQuery: /raw/,
        type: 'asset/source',
      },
    ]
  }
}
```
## Steps to reproduce
Create any react app, use styled-components and bootstrap css-cascading style sheet, and following the setup mentioned above.
When opening the browser devTool, you find this wrong selector.
## Expected Behavior
```css
.navbar-light .navbar-toggler-icon {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
}
.navbar-dark .navbar-toggler-icon {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
}
.alert-primary {
  color: #004085;
  background-color: #cce5ff;
  border-color: #b8daff;
}
```
## Actual Behavior
```css
.navbar-light .navbar-toggler-icon .navbar-dark .navbar-toggler-icon .alert-primary {
  color:#004085;
  background-color:#cce5ff;
  border-color:#b8daff;
}
```
- browser devTool
![CleanShot 2023-08-19 at 22 34 38](https://github.com/styled-components/styled-components/assets/88970984/7c6604db-6368-4aed-9317-f52a8ea61ea9)
