### ISSUE TITLE
`react-dom` should be an optional peerDependency

### ISSUE THREAD

**Issue by wojtekmaj** [styled-components/styled-components#4257]
## System:
 - OS: macOS 14.2.1
 - CPU: (8) arm64 Apple M2
 - Memory: 154.02 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 20.9.0 - /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-db98c2cc/node
 - Yarn: 4.0.2 - /private/var/folders/3y/swkjq1x101b76mzjgt4pm2d80000gp/T/xfs-db98c2cc/yarn
 - npm: 10.1.0 - /usr/local/bin/npm
 - bun: 1.0.23 - ~/.bun/bin/bun
## npmPackages:
 - styled-components: ^6.1.8 => 6.1.8 

## Steps to reproduce

Install styled-components in a project that does not use react-dom (e.g. React Native project).

## Expected Behavior

Yarn not to produce a warning

## Actual Behavior

Yarn produces the following warning: 

```
➤ YN0002: │ bubblejoy-app-native@workspace:. doesn't provide react-dom (p9a0a1), requested by styled-components.
```

and thus needs a workaround:

```yml
packageExtensions:
  styled-components@*:
    peerDependenciesMeta:
      react-dom:
        optional: true
```
