### ISSUE TITLE
[v2] data urls in css break parsing

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#433]
## Version
@next, so recent v2.0. I can't post a reproduction, webpackbin just hangs when trying to add `styled-components@next` or `@2.0`.

## Steps to reproduce
```js
styled.div`
    background-image: url(data:image/png;etc); /* quoting the url doesn't help */
`
```
## Expected Behavior
it works like in v1

## Actual Behavior
it breaks:
```css
.gMVerY {
    background-image: url(data:image/png;}.other-component-1hm8ero {}.kWlwJm {position: absol…: 3px;left: -300px;width: 1290px;background-color: rgba(120, 120, 120, 0.8);
}
```
