### ISSUE TITLE
v2 prerelease feedback

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#453]
If you're using the v2 pre-release, please let us know in a comment below if it works well for you! If you encounter bugs, **please submit individual issues for them**!

> To try the v2 prerelease, use `npm install styled-components@next babel-plugin-styled-components` and add the plugin to your Babel configuration like a regular Babel plugin. The plugin is optional as it only provides consistent naming for SSR as well as some pre-processing.

**Comment by garmjs** [comment]
Im not using v2 but just tested and i see if you use minify option it break parsing

I'm using 
 `node v7.0.0`
`webpack 2`
`styled-components@next` with `babel-plugin-styled-components`

## Steps to reproduce
```
const Box = styled.div`
  background-color: orange;
  width: 100px;
  height: 100px;
`
```

## Expected Behavior
```.app__Box-75m7jb {} .dwklpT {background-color: orange;width: 100px;height: 100px;}```

## Actual Behavior
```.app__Box-75m7jb {}.dwklpT {background-color: orange;width: 100px;height: 100px;}```

![kapture 2017-02-05 at 22 01 48](https://cloud.githubusercontent.com/assets/5017156/22629859/0f1eb9c8-ebef-11e6-87ac-5ab52d19c4bf.gif)

**Comment by svrcekmichal** [comment]
I've been using it little bit and wanted to do something like this:
```
const Button = styled.button`...`

const Block = styled.div`
&:hover > ${Button} {
   ...
}
`
```
but I was not able to make it work, so maybe there is issue between chair and computer :D . Component `displayName` works great to me and didn't found any bug now.

**Comment by axelson** [comment]
As I reported in #434 I'm successfully using v2 in a small internal project (that uses create-react-app). Didn't have to make any changes.

**Comment by three60five** [comment]
Do the changes in v2 around attr mean that using tachyons and styled-components together will be simplified?

**Comment by geelen** [comment]
@three60five yep! #365 is the PR that adds that.

**Comment by IljaDaderko** [comment]
Just tried `2.0.0-3` in a `react-native@0.41.2` project, seems to be working like before, without changing anything.

**Comment by adjnor** [comment]
When I try using babel-plugin-styled-components, I get this error in the console:
`__WEBPACK_IMPORTED_MODULE_3_styled_components__.default.a.withConfig is not a function at eval ...`
The component giving the error being defined as so:
```
const MyComponent = styled.a`{
// styles here
}`;
```
I'm using styled-components v2.0.0-4 and babel-plugin-styled-components v1.0.0

**Comment by garmjs** [comment]
@adjnor `styled-components` is using tag functions [Computing tag functions for ES6 template literals](http://www.2ality.com/2016/11/computing-tag-functions.html)

remove bracket
```
const MyComponent = styled.a`
// styles here
`;
```

**Comment by adjnor** [comment]
@garmjs Thanks, that fixed it! I still think the error I got is a bug though, the brackets inside the tagged literal is valid syntax as far as I know, otherwise how would styled-components work? With that said, I was using the brackets because of a quirk with atom which wasn't properly highlighting the css code without the brackets but now it's fine.

**Comment by mxstbr** [comment]
> the tagged literal is valid syntax as far as I know, otherwise how would styled-components work?

Nope, you don't need brackets at all. See any example in the docs 😊

**Comment by kopax** [comment]
I am trying to install __styled-components/babel-plugin-styled-components__ with webpack (react-boilerplate).

I have added in my _internals/webpack/webpack.dist.babel.js_

```jsx
{
  "plugins": ["styled-components"]
}
```

```bash
> cross-env NODE_ENV=production webpack --config $(pwd)/internals/webpack/webpack.dist.babel.js --color -p --progress

/bootstrap-styled/node_modules/webpack/bin/webpack.js:315
                throw e;
                ^

TypeError: arguments[i].apply is not a function
```

**Comment by thysultan** [comment]
@kopax #1 & #2 might be because stylis removes all comments(line, block) and #3 the css syntax shouldn't be different, can you post an example of some css that is processed incorrectly.

**Comment by kopax** [comment]
@thysultan #1 and #2, the appended css that appear in the `<style>` tag doesn't have any comment.

But my module using styled-components made with webpack is compressed in a .js file. In this file I can still see many comments and the filesize is 416kb instead of 422kb. So this appear not to work!

This is a component that doesn't work with styled 2.0 : 

https://gist.github.com/kopax/597f0801ab3e87ba1adfe6b72ef77967

Style tag generated css : http://pastebin.com/87KzCi0Q

And this is the one corrected (added semicolon to every last css rules)

https://gist.github.com/kopax/d2672ceb7121d820de5f1e7cd7c49457

Style tag generated css : http://pastebin.com/nMmUCGVB

**Comment by thysultan** [comment]
@kopax Does the second one(with semicolons) also not work?

**Comment by kopax** [comment]
@thysultan I have updated mine, It was still missing semicolon at the beggining (3).

It work afterthat, but I am currently correcting all the components that are not using semicolon for last rules, they are all broken.

**Comment by thysultan** [comment]
@kopax It actually should work without semicolon(the last property) since that is valid css, i'll look into this.

**Comment by kopax** [comment]
Thank you @thysultan , do you have an idea for the deprecation warning and all the other points ?
I am very surprised that there is no error handling.

**Comment by thysultan** [comment]
.6 & .7, it's a bug in stylis, i've patched it in v1.1.12, thanks for finding this. The other points i don't know.

**Comment by kopax** [comment]
How can I get the patched version ? I am correcting everything by hand.

**Comment by thysultan** [comment]
@kopax re-install, i think npm should pull the latest version patch of stylis.

**Comment by kopax** [comment]
Which version? I have fixed in my package.json : 

    "babel-plugin-styled-components": "1.0.0",
    "styled-components": "2.0.0-4",

This may sound a little dumb but how did you patch your `package.json` without releasing anything ?

**Comment by k15a** [comment]
`rm -rf node_modules && npm install` but this might not work if you're using webpack@2

**Comment by kopax** [comment]
I am using  `"webpack": "2.2.0"`. How is this webpack related?

**Comment by k15a** [comment]
Because Webpack will use the bundled version of styled-components if configured correctly which is not updated currently.

**Comment by kopax** [comment]
I am not aware of this, would you mind share a link where I can read ? Using webpack 2.0, we will have to wait for the next official npm release right ? But it's also possible to install from a github directly, for that, I need to see your commit.

**Comment by k15a** [comment]
Webpack checks for the fields [`browser, module, main`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) in your package.json (in this case styled-components one) for the file it will take as the module entry. In the case of styled-components it will take the [`"module": "dist/styled-components.es.js"`](https://github.com/styled-components/styled-components/blob/master/package.json#L8) line which directs to a bundled version (with all dependencies except React). This is currently a problem because you will only get the version of the dependencies which were released as styled-components got last released, which might be some outdated one.

**Comment by kopax** [comment]
I wonder if I install stylis myself as a dependency of the project if my dependency will be prioritized than the one from styled. I will wait for the next release of styled-components. I manage to restore my project by correcting every missing semicolon and correcting every comment that were using apostrophe. Thanks for all the explanation.

**Comment by thysultan** [comment]
@kopax 

> correcting every comment that were using apostrophe

Was this causing problems, can you share an example?

**Comment by kopax** [comment]
@thysultan yes I was having issues in components that had semicolon to each css rules. I manage to generate the css by removing `'` in comments from that file. I don't have any example to share but if it again, I'll share the example.

**Comment by santaclauze** [comment]
Hey, been testing v.2. It's up and running.

I have encountered similar issues to the discussion above. Semicolons are the worst I reckon.

I wanted to know if some css is not acceptable anymore. Prior to v.2, the following css worked:

```css
${mediaBreakpointUp(
      'sm',
      props.theme['$grid-breakpoints'],
      `
        &.card-deck {
          display: flex;
          flex-flow: row wrap;
        
          .card {
            display: flex;
            flex: 1 0 0;
            flex-direction: column;  
            &:not(:first-child) { margin-left: ${props.theme['$card-deck-margin']}; }
            &:not(:last-child) { margin-right: ${props.theme['$card-deck-margin']}; }
          }
        }
      `
    )}
```

But since v.2 it crashes. After debugging, I realized that the following lines made the css crash:
```css
&:not(:first-child) { margin-left: ${props.theme['$card-deck-margin']}; }
&:not(:last-child) { margin-right: ${props.theme['$card-deck-margin']}; }
```

If I delete one of them, it works fine, but for some reason, when both are applied, they make the css injection crash. 

Also, this works:

```css
${mediaBreakpointUp(
      'sm',
      props.theme['$grid-breakpoints'],
      `
        &.card-group {
          display: flex;
          flex-flow: row wrap;
      
          .card {
            flex: 1 0 0;
      
            + .card {
              margin-left: 0;
              border-left: 0;
            }
      
            ${ifThen(props.theme['$enable-rounded'],
              `                
                  background-color: red;
                
              `
            )}  
          }
        }
      `
    )}
```

But not:

```css
${mediaBreakpointUp(
      'sm',
      props.theme['$grid-breakpoints'],
      `
        &.card-group {
          display: flex;
          flex-flow: row wrap;
      
          .card {
            flex: 1 0 0;
      
            + .card {
              margin-left: 0;
              border-left: 0;
            }
      
            ${ifThen(props.theme['$enable-rounded'],
              `     
                  .car-img-bottom {    
                      background-color: red;
                  }
              `
            )}  
          }
        }
      `
    )}
```

These behavios are quite bizarre. I am not sure if they come from a bug here, or due to another small issue like 'semicolons' who have been a bit of a hassle for me.
