### ISSUE TITLE
Best practice for referencing other styled-components

### ISSUE THREAD

**Issue by yaycmyk** [styled-components/styled-components#523]
Could you document somewhere how styles that relate to another component should be handled?

For instance, say I have ComponentA and ComponentB. ComponentB has a style that if it comes after ComponentA it should add a right margin, e.g.

```css
.component-a + .component-b {
    margin-right: 10px;
}
```

How would you do something like this with `styled-components` without having to add additional identifiers to the components themselves so they can be locked-onto via selectors?

**Comment by k15a** [comment]
This will be added in v2. Look at #142. Basically you're doing:

```JS
const A = styled.div``

const B = styled.div`
  ${B} + & {
    margin-right: 10px;
  }
`
```

**Comment by reanimatter** [comment]
Not sure how it is supposed to work with selectors like
```css
.comp + .comp {
  margin-left: 10px;
}
```

the following setup

```javascript
const Comp = props => {
  return <div className={props.className} />
};

const StyledComp = styled(Comp)`
  width: 16px;
  height: 16px;
  background: red;
  display: inline-block;
  ${StyledComp} + & {
    margin-left: 8px;
  }
`;
```

produces

```css
/* sc-component-id: sc-htpNat */
.sc-htpNat {} .flaKOJ{width:16px;height:16px;background:red;display:inline-block;} + .flaKOJ{margin-left:8px;}
```

which obviously doesn't work. What am i missing?
