### ISSUE TITLE
[V2] :global(.ReactModalPortal) prefix render CSS rule with vendor prefix

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#552]
I am trying to customize __react-modal__.

This Component has to work with it's parents and body

    body.ReactModal__Body--open > .ReactModalPortal > .modal > MyComponent

On 3 attempt, `:global()` injected twice correctly and last time fail because it adds a vendor prefix.

## Version
2.0.0-5

## Reproduction
http://www.webpackbin.com/NyNB1yG9z

You will have to open your __developer console__ and copy the `<style>` element that own the css of MyComponent, then past it in a [unminify](http://unminify.com) in order to read it.

## Steps to reproduce

I am trying to use `:global()` like this : 

```jsx
styled.div`
:global(body.ReactModal__Body--open) { overflow: hidden; }
:global(.modal) { ... }
:global(.ReactModalPortal) { ... }
```

## Expected Behavior

but the css generated looks like this:

```css
body.ReactModal__Body--open {
    overflow: hidden;
}

.modal {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1050;
    overflow: hidden;
    outline: 0;
    background-color: rgba(0, 0, 0, .5);
}

.ReactModalPortal .fade {
    opacity: 0;
    -webkit-transition: opacity .15s linear;
    transition: opacity .15s linear;
}

.ReactModalPortal .fade.show {
    opacity: 1;
}

.ReactModalPortal .collapse {
    display: none;
}

.ReactModalPortal .collapse.show {
    display: block;
}

.ReactModalPortal tr.collapse.show {
    display: table-row;
}

.ReactModalPortal tbody.collapse.show {
    display: table-row-group;
}

.ReactModalPortal .collapsing {
    position: relative;
    height: 0;
    overflow: hidden;
    -webkit-transition: height .35s ease;
    transition: height .35s ease;
}
```

## Actual Behavior

but the css generated looks like this:

```css
body.ReactModal__Body--open {
    overflow: hidden;
}

.modal {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1050;
    overflow: hidden;
    outline: 0;
    background-color: rgba(0, 0, 0, .5);
}

.bMEHgJ .ReactModalPortal .fade {
    opacity: 0;
    -webkit-transition: opacity .15s linear;
    transition: opacity .15s linear;
}

.bMEHgJ .ReactModalPortal .fade.show {
    opacity: 1;
}

.bMEHgJ .ReactModalPortal .collapse {
    display: none;
}

.bMEHgJ .ReactModalPortal .collapse.show {
    display: block;
}

.bMEHgJ .ReactModalPortal tr.collapse.show {
    display: table-row;
}

.bMEHgJ .ReactModalPortal tbody.collapse.show {
    display: table-row-group;
}

.bMEHgJ .ReactModalPortal .collapsing {
    position: relative;
    height: 0;
    overflow: hidden;
    -webkit-transition: height .35s ease;
    transition: height .35s ease;
}
```
