### ISSUE TITLE
[V2] /* */ Comments fail to parse when apostrophe is used

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#554]
I have valid comment that crash the css rendering when using apostrophe `'` only once.

We had to correct `/* don't do this */` => `/* do not do this */`

## Version
2.0.0-5

## Reproduction
http://www.webpackbin.com/NkoxEJM9G

## Steps to reproduce

```jsx
const HelloWorld = styled(HelloWorldUnStyled)`
  // will work
  border-left: 2px solid red;
  // ' <== this work but not when used with comment /**/'
  border-bottom: 2px solid blue;
  /* this comment is allowed because use 'not' only one apostrophe */
  border-top: 2px solid yellow;
  /* this comment can't be allowed because use only one apostrophe */
  border-bottom: 2px solid green;
`;
```

## Expected Behavior

```css
.vendor {
  border-left: 2px solid red;
  border-bottom: 2px solid blue;
  border-top: 2px solid yellow;
  border-bottom: 2px solid green;
}
```

## Actual Behavior

```css
.vendor {
  border-left: 2px solid red;
  border-bottom: 2px solid blue;
  border-top: 2px solid yellow;
}
```
