### ISSUE TITLE
[V2] :global(body) produce wrong css by prefixing with `body body` the first rule

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#569]
In version `2.0.0-7` I have the  `:global(body)`  that inject a wrong CSS : 

## Version
2.0.0-7

## Reproduction

https://www.webpackbin.com/bins/-KenI7hFjUVw-a3OHFBO

## Steps to reproduce

Create the following 

```jsx
const Title = styled.h1`
  height: 300px;
  border: 1px solid red;

  .bug { 
    border: 1px solid blue; 
  }

  :global(body) {
    #browser, .bug { 
      height: 100%; 
    }
  }

`;
papayawhip background
const Wrapper = styled.section`
  padding: 4em;
  background: papayawhip;
`;

export default () => {
  return (
    <Wrapper>
      <Title><div className="bug">Red and Blue lines should touch each over</div></Title>
    </Wrapper>
  );
}
```

## Expected Behavior

```css

.dXEqgY {
    height: 300px;
    border: 1px solid red;
}

.dXEqgY .bug {
    border: 1px solid blue;
}

body .bug {
    height: 100%;
}

.sc-bwzfXH {}

.gzMTbA {
    padding: 4em;
    background: papayawhip;
}
```

## Actual Behavior

```css

.dXEqgY {
    height: 300px;
    border: 1px solid red;
}

.dXEqgY .bug {
    border: 1px solid blue;
}

body body .bug {
    height: 100%;
}

.sc-bwzfXH {}

.gzMTbA {
    padding: 4em;
    background: papayawhip;
}
```
