### ISSUE TITLE
Don't work when use require() in style

### ISSUE THREAD

**Issue by forsigner** [styled-components/styled-components#623]
Don't work when use require() in style

```js
const IconBack = styled.i`
  display: inline-block;
  height: 40px;
  width: 40px;
  background-image: ${require('./icon_back.png')};
`;

const Back = () => (
  <IconBack></IconBack>
);
  
```

It generate styles:
```css
.kQQGvE {
    display: inline-block;
    height: 40px;
    width: 40px;
    background-image: data:image/png;
}
```

I expect:
```css
.kQQGvE {
    display: inline-block;
    height: 40px;
    width: 40px;
    background-image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAEG0lEQVRYhb3ZW4hVZRTA8d9sjxXmpdAg0/Qh1MrsplLUQ3kpgpIIqimyQIQumHZ5KiqDUuhFQiqISjKz1BIi5qXItAt0U7uplfbUOGUPTuVlpGa89LC+04x6Zubss7ctOJy9z/7WWv+zv/2tb621m/YtGaMByTAV0zAF4zEKp6brHfgVO7AJG7ARh/M6quQcPxrzcAf24EO8jZ+wE/vTuME4GxNwBV7BMLyBF9BWNuBwPIXbsRzXY0sf4/9In+/wVvptEubge6zCQrT35zirA+5WbMMhMZUP9wPXm2xJuuOSrW1o7k+prztYwXOYgVniGSpD2rEAK/AmrsZ8HKw1uLc7OAjvYKxYBGXB9ZRNyfbY5GtQvYAV8Yx04EbsPQFwVdmbfHQkn8fNaC3A59GEu9B1AuGq0pV8NSXfR8mxgM3imZuNzhKcjxPxsj/pTD5niEhRE3A4luI25UzrLBFSvhSxsD/Zm3wvxRm1ABeJoLu5BLhmrMUpYnXW+4c3YzWerv7QlLa6MfhWxLndBeHm4GUMwD+4BS059EeILfJitFbv4H14rQS4eViW4DpwQ044iWF5YpKlz+xkuIg8ojsC7MF1WNegrWWJKauIVbYHWwvALcJj6bgd1+LrAva24S9MrWA6PmjQUBOexQPpfBeuSQ6KyjpMyzAZXzRgYABe6gH3C64qCU5imlIROduPOZUHikVVDao/YyZaS4KTmCZUMBK/5VCsiHh5YzrfKqb19xLhiIx8ZIYh2JdDsVk33DciXSobjmAaUo2DRwoYKqLbr2SCdGgOnTV4Nx1fgo9wZrlYSDObidBwVg7Fg2L7WpXOJwnIhsrDPmQUdmXYjvNyKnfhTlGtEZHgE5xTGh7nYnsmMojLGzBwCHeL9IhI3T/F+aXgBdOmTBTVMxs0cgQPYnE6H4mPcWlhvGDakOErnIaJBYw9jkfT8Qisx5UF7E3E6diYiXbESswtYBCewf3irg7D+xqfmbmJ6XA1YR0tugATlJuw/i0K/7wJ63ZchLZqoG4TqfbCgnDwqujddIqUfy0uyKH/hGiXtHF0HboQP4gkoGhdsgYHkqOT1b8RTBaF03+RoGfR1C5Sp1U5DPYlLbgQl+GzOsYPTb4f0qOp1FSjP/iiCBc3+38KdyJ9WyuSjnt6XqjVWViQvlckxRMtA/F6Op5/7MVagJ0iER0mkoIyprs3GZp8DE4+j+tm9NbdOiByvlbdXaiyZUqy3Yqbks/jpK8GZhfuFau7Rey5w0sAq7ZYWvBk8tHrs15Ph3W1SKlOEhX/EvniWlUmJt0dydYk3Slbr1Jvj3q3qPQXi+3sPfwpSsPPReTfqbt0GCKa6ONF42im2FtXSjtEnX5rhpl6pPoaYroIruPFdjk4Xd+fIHaIoL9eg68h/gUoXO1nBEe0GwAAAABJRU5ErkJggg==" ;
}
```
