### ISSUE TITLE
keyframes in front of font @import 

### ISSUE THREAD

**Issue by PengyuanZhao** [styled-components/styled-components#673]
I'm using `injectGlobal` to `@import` google fonts and `keyframes` animation in anther place. But the `keyframes` ends up siting in front of  `@import` in final CSS in which case `@import` becomes invalid.

```css
@keyframes eMLfYp {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@import url('https://fonts.googleapis.com/css?family=Nunito+Sans:300,300i,400,400i,700,700i');
```

Thanks for any help on this.
