### ISSUE TITLE
Unused style rule found on page

### ISSUE THREAD

**Issue by ooade** [styled-components/styled-components#682]
**Version:** v2.0.0-15 
I have this on my server side rendered app:
```js
const StyledDiv = styled.div`
  background-color: papayawhip;
`;

const Title = styled.h1`
  color: red;
  font-size: 50px;
`;

export default () => (<StyledDiv><Title>My page</Title></StyledDiv>)
```
It generated this stylesheet
```css
.ljxohu-0 {}.fwLwBr {background-color: papayawhip;},.ljxohu-1 {}.eOZnAk {color: red;font-size: 50px;}
```
I don't know why we should be having `.ljxohu-0 {}` or `.ljxohu-1 {}` on the page???
