### ISSUE TITLE
@media directive ignored if no other styles are present in Styled Component

### ISSUE THREAD

**Issue by mschipperheyn** [styled-components/styled-components#688]
I found that a media definition that I use is completely removed, if there are no other styles in the component definition or the style definitions occur after the @media statement (2.0.0-15) 

media definition not present in css:
```JS
export const Parallax = styled.div`

    @media screen and (min-width: ${container('xs')}){
        position:absolute;
        perspective: 300px;
        width:100%;
        height:100%;
        overflow-x: hidden;
        overflow-y: auto;
        scroll-behavior: smooth;
    }
`;
```
media definition not present in css:
```JS
export const Parallax = styled.div`

    @media screen and (min-width: ${container('xs')}){
        position:absolute;
        perspective: 300px;
        width:100%;
        height:100%;
        overflow-x: hidden;
        overflow-y: auto;
        scroll-behavior: smooth;
    }

    padding: 0;

`;
```

media definition present in css:
```JS
export const Parallax = styled.div`

    padding: 0;

    @media screen and (min-width: ${container('xs')}){
        position:absolute;
        perspective: 300px;
        width:100%;
        height:100%;
        overflow-x: hidden;
        overflow-y: auto;
        scroll-behavior: smooth;
    }
`;
```

**Comment by philpl** [comment]
Is this a bug with styled possibly, @Thysultan?

**Comment by thysultan** [comment]
I get the right output with the following input

Input

```css
@media screen and (min-width: 400px){
        position:absolute;
        perspective: 300px;
        width:100%;
        height:100%;
        overflow-x: hidden;
        overflow-y: auto;
        scroll-behavior: smooth;
}

padding: 1px;

```

Output

```
@media screen and (min-width: 400px) {
    #id {
        position: absolute;
        perspective: 300px;
        width: 100%;
        height: 100%;
        overflow-x: hidden;
        overflow-y: auto;
        scroll-behavior: smooth;
    }
}
#id {
    padding: 1px;
}
```
