### ISSUE TITLE
animation in li nth child

### ISSUE THREAD

**Issue by gmchaturvedi1** [styled-components/styled-components#724]
kindly suggest how to write the follwing code in styled component:

```css
li:nth-child(4) {
  animation: xfade 16s 0s infinite;
}
li:nth-child(3) {
  animation: xfade 16s 4s infinite;
}
li:nth-child(2) {
  animation: xfade 16s 8s infinite;
}
li:nth-child(1) {
  animation: xfade 16s 12s infinite;
}
@keyframes xfade{
  17% {
    opacity:1;
  }
  25% {
    opacity:0;
  }
  92% {
    opacity:0;
  }
}
```

regards
gmchaturvedi

## Version
1.0.5

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
