### ISSUE TITLE
composite css rules

### ISSUE THREAD

**Issue by randomvasya** [styled-components/styled-components#822]
I have this kind of html:
```html
<button class="arrow-button">
    <div class="rectangle">button</div>
    <div class="triangle">
        <div class="triangle-background"></div>
    </div>
</button>
```
on hover button parts must change color, one of this rule:
```css
.arrow-button:hover:not(:disabled) .rectangle {
    background: linear-gradient(#3b8d13 0, #307e0a 100%);
    border: 1px solid rgba(8, 73, 2, .7);
    border-bottom: 1px solid rgba(19, 71, 4, .8);
    border-right-style: none;	
}
```
How can I write such component in react? Didn't found something about that in your docs
