### ISSUE TITLE
v2.0.1 breaks inner styles referenced by classname

### ISSUE THREAD

**Issue by erikras** [styled-components/styled-components#895]
```jsx
const Container = styled.div`
  margin: 20px;
  .inner-element {
    border: 3px solid green;
  }
}
`

<Container>
  <div className="inner-element">
    This is inner element. It should have a green border. But it doesn't. 😢
  </div>
</Container>
```

## Version
2.0.1

## Reproduction

[![Edit Styled Components v2.0.1 Bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jqVV7kAKv)

Here it is _working_ in `v2.0.0`:

[![Edit Styled Components v2.0.1 Bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6ppv6oVO)

**Comment by k15a** [comment]
@thysultan did you fixed that as well?

**Comment by thysultan** [comment]
There's an extra `}` at the end.

```css
styled.div`
  margin: 20px;
  .inner-element {
    border: 3px solid green;
  }
} <---
```

**Comment by erikras** [comment]
Whoa. The silent failure strikes again. 😦

Good eye!

I guess I have to go search for these in my code base...

**Comment by thysultan** [comment]
stylis v3.1.4 will gloss-over and monkey-patch this mistake if it finds it, this can also apply to something like

```scss
	margin: 20px;
	.b {
	  border: 3px solid green;
	}
}
	.c {
		color:red;
	}
	color:red;
}
```
