### ISSUE TITLE
[Bug] Server side rendered global print styles

### ISSUE THREAD

**Issue by codepunkt** [styled-components/styled-components#957]
## Version
2.1.0

## Steps to reproduce
server side render global print styles, e.g.
```javascript
injectGlobal`
  @page {
    size: A4 landscape;
  }
  @page :left {
    margin-left: 3cm;
  }
  @media (max-width: 700px) {
    html {
      background: palevioletred;
    }
  }
`
```

## Expected Behavior
style tag in server side rendered head with
```css
@page{size: A4 landscape;}
@page :left{margin-left: 3cm;}
@media (max-width: 700px){html{background: palevioletred;}}
```

## Actual Behavior
style tag in server side rendered head with
```css
@page{{size: A4 landscape;}}
@page :left{{margin-left: 3cm;}}
@media (max-width: 700px){html{background: palevioletred;}}
```
